gp-jin:
	python3 run_gp.py --task=Jin-1 &
	python3 run_gp.py --task=Jin-2 &
	python3 run_gp.py --task=Jin-3 &
	python3 run_gp.py --task=Jin-4 &
	python3 run_gp.py --task=Jin-5 &
	python3 run_gp.py --task=Jin-6 &

mksr-jin:
	python3 run_mksr.py --task=Jin-1 &
	python3 run_mksr.py --task=Jin-2 &
	python3 run_mksr.py --task=Jin-3 &
	python3 run_mksr.py --task=Jin-4 &
	python3 run_mksr.py --task=Jin-5 &
	python3 run_mksr.py --task=Jin-6 &